### ISSUE TITLE
How do you use it?

### ISSUE THREAD

**Issue by Yeetov** [katlyn/userpfp-bot#1]
How do you use the bot? What file to run, what config and will it automatically approve or can we choose to approve or deny the pfp requests using the bot?

**Comment by katlyn** [comment]
The bot hasn't been set up in a state that's ready to be deployed yet, but once it is it will be containerized and be able to run with docker or another container service. Example config is in [example.env](https://github.com/katlyn/userpfp-bot/blob/owo/example.env).

It does not automatically approve - requests are sent to a configured channel and someone with the appropriate role is able to approve or reject requests.
![image](https://github.com/katlyn/userpfp-bot/assets/17418611/8ab1c719-b6c4-48a1-9fee-e96befaee0b5)

**Comment by Yeetov** [comment]
How do you run projects with docker?

**Comment by Yeetov** [comment]
.

**Comment by Yeetov** [comment]
.
